FROM python:3.14.5-slim

WORKDIR /backend

COPY requirements-api.txt requirements-api.txt

RUN pip install --no-cache-dir --upgrade -r requirements-api.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]